name: CI/CD Pipeline

on:
    push:
        branches:
            - main
        tags:
            - 'v*.*.*'
    workflow_dispatch:

jobs:
    pipeline:
        uses: oberon-oss/github-workflows/.github/workflows/maven-pipeline.yml@v2
        secrets: inherit